Document: pyroute2
Title: Debian pyroute2 Manual
Author: <insert document author here>
Abstract: This manual describes what pyroute2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyroute2/pyroute2.sgml.gz

Format: postscript
Files: /usr/share/doc/pyroute2/pyroute2.ps.gz

Format: text
Files: /usr/share/doc/pyroute2/pyroute2.text.gz

Format: HTML
Index: /usr/share/doc/pyroute2/html/index.html
Files: /usr/share/doc/pyroute2/html/*.html
